// <auto-generated />
namespace EF6.Demo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EF6Demo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EF6Demo));
        
        string IMigrationMetadata.Id
        {
            get { return "201712251015042_EF6.Demo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
